version: '2'

services:
  # tweepy
  tweepy:
    image: juergenp/tweepy_textblob:latest

    depends_on:
      - elastic

    volumes:
      - ${TWEEPY_CONFIG}:/usr/src/app/config.py
      - ${TWEEPY_SRC}:/usr/src/app/sentiment.py


  # Elasticsearch
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1

    ports:
      - "${PORT_ELASTIC}:9200"
      - "9300:9300"

    environment:
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft:     -1
        hard:     -1

    mem_limit:    1g

    volumes:
      - ${ELASTIC_CONFIG}:/usr/share/elasticsearch/config/elasticsearch.yml
#      - local:/usr/share/elasticsearch/data

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.1

    depends_on:
      - elastic

    volumes:
      - ${KIBANA_CONFIG}:/usr/share/kibana/config/kibana.yml

    ports:
      - ${PORT_KIBANA}:5601
